
services:
  # web:
  #   build: ./web
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./web:/app
  #     - /app/node_modules
  #   env_file:
  #     - ./web/.env
  #   environment:
  #     - NODE_ENV=development
  #     - NEXT_PUBLIC_API_URL=http://api:8080
  #   depends_on:
  #     - api
  #   container_name: kpi_web
  #   restart: unless-stopped
  #   tty: true
  #   stdin_open: true
  #   command: ["bun", "run", "dev"]

  api:
    build: ./api
    container_name: kpi_api
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app
      - /app/node_modules
    env_file:
      - ./api/.env
    depends_on:
      - redis
    command: ["npm",'run',"start:dev"]
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    container_name: kpi_redis

volumes:
  redis_data: